name: remote ssh command

on:
  push:
    tags:
      - v*
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: build & start app
        uses: appleboy/ssh-action@v1.0.3
        with:
          proxy_key: ${{ secrets.DEPLOY_SSH_PROXY_SECRET_KEY }}
          proxy_host: ${{ secrets.DEPLOY_SSH_PROXY_HOST }}
          proxy_username: ${{ secrets.DEPLOY_SSH_PROXY_USER }}
          proxy_passphrase: ${{ secrets.DEPLOY_SSH_PROXY_PASSPHRASE }}
          host: ${{ secrets.DEPLOY_SSH_HOST }}
          username: ${{ secrets.DEPLOY_SSH_USER }}
          port: ${{ secrets.DEPLOY_SSH_PORT }}
          password: ${{ secrets.DEPLOY_SSH_PASSWORD }}
          script: |
            echo "${GITHUB_REF##*/}"
            kill $(ps -e -o pid,cmd | grep "npm start" | grep -v grep | awk '{ print $1 }')
            git clone git@github.com:cacaoMath/rss_client.git -b ${GITHUB_REF##*/}
            cd rss_client
            npm ci && npm build
            nphup npm start &
