name: remote ssh command

on:
  push:
    tags:
      - v*
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          proxy_key: ${{ secrets.DEPLOY_SSH_SECRET_KEY }}
          proxy_host: ${{ secrets.DEPLOY_HOST }}
          proxy_username: ${{ secrets.DEPLOY_SSH_USER }}
          proxy_passphrase: ${{ secrets.DEPLOY_SSH_PASSPHRASE }}
          host: ${{ secrets.DEPLOY_PROXY_HOST }}
          username: ${{ secrets.DEPLOY_PROXY_USER }}
          port: ${{ secrets.DEPLOY_PROXY_PORT }}
          password: ${{ secrets.DEPLOY_PROXY_PASSWORD }}
          script: |
            whoami
            ls -la
