name: test

on:
  push:
    branches:
      - issues/*
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 19
          cache: 'npm'
      - run: npm ci
      - run: npm test -- --coverage
